# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'CGRImage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CGRImage', :path => '../'

  # Pods for CGPaint

end
